services:
  backend:
    build: ./backend
    container_name: cargo_camp_backend
    restart: always
    network_mode: "host"   # вот ключевое изменение
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: 81.163.27.147
      DB_USER: cargocamp            # поменяй на своего пользователя
      DB_PASSWORD: root        # поменяй на пароль
      DB_NAME: cargo_camp
    volumes:
      - ./uploads:/app/uploads
      - /root/cargocamp-secrets/firebase-service-account.json:/app/secrets/firebase-service-account.json:ro
      - ./contracts:/app/contracts
    command: ["npm", "start"]

  frontend:
    build: ./frontend
    container_name: cargo_camp_frontend
    restart: always
    ports:
      - "3001:80"
    env_file:
      - ./frontend/.env
    environment:
      REACT_APP_API_URL: http://localhost:5001
      REACT_APP_SOCKET_URL: http://localhost:5001
    networks:
      - cargo_camp_net

  admin-panel:
    build: ./admin-panel
    container_name: cargo_camp_admin-panel
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./admin-panel/.env
    environment:
      REACT_APP_API_URL: http://localhost:5001
      REACT_APP_SOCKET_URL: http://localhost:5001
    networks:
      - cargo_camp_net

networks:
  cargo_camp_net:
    driver: bridge
