version: '3.9'

services:
  backend:
    build: ./backend
    container_name: cargo_camp_backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: host.docker.internal  # обязательно сервер хост
      DB_USER: root            # поменяй на своего пользователя
      DB_PASSWORD: root        # поменяй на пароль
      DB_NAME: cargo_camp
    networks:
      - cargo_camp_net
    volumes:
      - ./uploads:/app/uploads
    command: ["npm", "start"]

  frontend:
    build: ./frontend
    container_name: cargo_camp_frontend
    restart: always
    ports:
      - "3001:80"
    env_file:
      - ./frontend/.env
    environment:
      REACT_APP_API_URL: http://localhost:5001
      REACT_APP_SOCKET_URL: http://localhost:5001
    networks:
      - cargo_camp_net

  admin-panel:
    build: ./admin-panel
    container_name: cargo_camp_admin-panel
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./admin-panel/.env
    environment:
      REACT_APP_API_URL: http://localhost:5001
      REACT_APP_SOCKET_URL: http://localhost:5001
    networks:
      - cargo_camp_net

networks:
  cargo_camp_net:
    driver: bridge
